// ══════════════════════════════════════════════════════════════════════════════════════════════
// DECK MASKS — MULTI-DECK MAP (BATCH 1, 2026-07-28)
// ----------------------------------------------------------------------------------------------
// Explicit, frozen walkability data for the four authored section decks. GENERATED OFFLINE and
// checked in as data; the game NEVER classifies pixels at runtime.
//
// WHY A MASK AND NOT MORE AUTHORED ROWS
// The two MAIN strips are single horizontal floor bands, so CITY_WALK_ROWS / CHAOS_WALK_ROWS
// describe them exactly and are still the authority for those two decks — this file does not
// touch them. The four section assets are not bands: they are decks with pillars, machine
// footings, railings and window walls scattered across an open floor, and no row range can
// describe that. Each one therefore gets a per-cell mask.
//
// WHY THE SECTIONS ARE SEPARATE DECKS AND NOT A TALLER STRIP (measured 2026-07-28)
//   * gradient NCC across every candidate seam peaked at 0.07-0.15 over a ±70px dx sweep and a
//     -120..+160px overlap sweep, with flat peaks that wander ±100px: there is no shared
//     structure, so there is nothing to stitch to.
//   * the widths do not match — 2172 / 1672 / 2184 — so any single rectangle leaves 250-256px
//     void columns beside the main strip.
//   * the edges are authored boundaries: upper ends on a railing or a floor edge, main begins on
//     a skyline or a window wall. lower_section_endless is a closed arena bordered on all four
//     sides.
// Stacking them would mean inventing art. Each asset is used exactly as drawn instead.
//
// FORMAT
//   cell            8 source pixels; at CITY_SCALE 3 that is 24 world px per cell
//   cols/rows       mask dimensions, floor(imgW/cell) x floor(imgH/cell)
//   bits            base64 of the row-major bitset, MSB first within each byte
//   cropTop/Bottom  rows of pure white padding stripped off the source image before masking.
//                   chaos_mode_map_upper_section.png carries 53 white rows on top and 49 on the
//                   bottom — real content is 622px tall, not 724. Every offset here is measured
//                   against the CONTENT box, never the canvas.
//   anchorCell      the deck side of the MAIN transition, chosen offline as a cell with two
//                   clear cells in every direction (>=120 world px of slack around a 32px player)
//
// CONNECTED COMPONENTS
// Only the largest component of each section is kept as gameplay floor. endless/upper has a
// second 1082-cell walkway with no authored route to the main plaza; it stays blocked rather
// than being joined by a bridge that the artist never drew.
//
// CLEANUP IS DETERMINISTIC: morphological opening severs pixel-thin bridges, closing fills
// pinholes, a second opening re-severs anything closing recreated, then small components are
// dropped. Minimum surviving corridor width is 3 cells (72 world px) for chaos and 5 cells
// (120 world px) for endless, against a 32 world px player diameter.
// ══════════════════════════════════════════════════════════════════════════════════════════════

export const DECK_MASKS = Object.freeze({
  endless: Object.freeze({
    upper: Object.freeze({
      file: 'assets/maps/new_endless/upper_section_endless.png',
      imgW: 2172, imgH: 724,
      cropTop: 0, cropBottom: 0,
      cell: 8, cols: 271, rows: 90,
      walkableCells: 4741, walkablePct: 19.4,
      componentsFound: 2,
      keptComponentCells: 4741,
      droppedComponentCells: [1082],
      anchorCell: [114, 50],
      bits:
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+AAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAB////AD/+AAAAAAAfAH//AAAAAAAAAAAAAAAAAAAAAAAAB/////////+AAAAAP////gAAAAAAAAAAAAAAAAAAAAAAAA//////////AAAAAH/////AAAAAAAAAAAAAAAAAAAAAAAAf/////////gAAAAD////////gAAAAAAAAAAAAAAAAAAAAP/////////wAAAAB////////wP+AAAAAAAAAAAAAAAAAAH/////////4AAAAA////////4H/4AAAAAAAAAAAAAAAAAP/////////8AAAAAf///////8D/8AAAAAAAAAAAAAAAAAH/////////+AAAAAP///////+B/+AAAAAAAAAAAAAAAAAD//////////wAAAAH///////AP//AAAAAAAAAAAAAAAAAB//////////4AAAAD//////8AH//gAAAAAAAAAAAAAAAAA//////////8AAAAB//////+AD//wAAAAAAAAAAAAAAAAAf//////////AAAAA//////+AB//4AAAAAAAAAAAAAAB/wP//////////gAAAA///////AA//8AAAAAAAAAAAAAD//4D//////////////////////gAf/+AAAAAAAAAAAAAB//8B//////////////////////wAP//gAAAAAAAAAAAAA//+A//////////////////////4AH//wAAAAAAAAAAAAA///Af/////////////////////8AD//4AAAAAAAAAAAAA///gP//////////////////////AB///8AAAAAAAAAAAA/////////////////Af////////8A///+APgAAAAAAAAD/////////////////AP//////////////AHwAAAAAAAAB/////////////////gH////////////////4AAAAAAAAB/////////////////wD////////////////8AAAAAAAAB/////////////////4B//////////////////8AAAAAAA/////////////////8A//////////////////+AAAAAAAf////////////////+A///////////////////+AAAAAAP/////////////////Af//////gAf//////////wAAAAAH///////wAD8D/////gP//Af//wAP//////////4AAAAAD///////4AAAB/////wHwAAP//4AH//////////8AAAAAAP//AD4AAAAAA/////4D4AAB//8AAB////4P///+AAAAAAAA/gB8AAAAAAf////8B8AAA//+AAA////4H////AAAAAAAAAAAAAAAAAAB///8AAAAAAf//AAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAA///+AAAAAAH/+AAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAfAAfAAAAAAD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
    }),
    lower: Object.freeze({
      file: 'assets/maps/new_endless/lower_section_endless.png',
      imgW: 1672, imgH: 941,
      cropTop: 0, cropBottom: 0,
      cell: 8, cols: 209, rows: 117,
      walkableCells: 5927, walkablePct: 24.2,
      componentsFound: 1,
      keptComponentCells: 5927,
      droppedComponentCells: [],
      anchorCell: [69, 23],
      bits:
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////+AAAAAAAAAAAAAAAf8AAAAAAAAAAAAP/////gAAAAAAAAAAAAAA/4AAAAAAAAAAAAf/////AAAAAAAAAAAAAAB/wAAAAAAAAAAAA/////+AAA///AAAAAAAAD/gAAAAAAAAAAAB/////8AAH//+AAAAAAAAH/AAAAAAAAAAAAD/4B//4H////8AAAAAAAAPgAAAAAAAAAAAAf8AD//wP//////+AAAAf//AAAAAAAAAAAAA/4AH//gf//////8AAAA//+AAAAAAAAAAAAB/wAP//A///////4AAAB//8AAAAAAAAAAAAD/gAf//5///////wAAAD//4AAAAAAAAAAAAH/AA///wAH/////gAAAH//wAAAAAAAAAAAAP+AB///gAP/////fAAAP/8AAAAAAAAAAAAAf/8D///AAf////++AAAf/4AAAAAAAAAAAAA//4H//+AA/////98AAAD4AAAAAAAAAAAAAB//wAA/8AB/////7/gAAHwAAAAAAAAAAAAB///gAB/4AD///gAH/AAAPgAAAAAAAAAAAAP///AAD///////AAP+AAAfAAAAAAAAAAAAAf//+AAH//////+AAf8AAA+AAAAAAAAAAAAA///8AAP//////8AA/4AAB8AAAAAAAAAAAAB///4AAf//////4AB/wAf//8AAAAAAAAAAAf///wAA///////+AD/gA///4AAAAAAAAAAA////AAB///////////AB///wAAAAAAAAAAB/gAAAD///////////+AD///gAAAAAAAAAAD/AAAAH/////////////////AAAAAAAAAAAH+AAAAP////////////////+AAAAAAAAAAAAAAAAAf////////////////8AAAAAAAAAAAAAAAAA//////////////AD4AAAAAAAAAAAAAAAAAB/////////////+AHwAAAAAAAAAAAAAAAAH///////AH/////8APgAAAAAAAAAAAAAAAAP/Af///+AP/////4AfAAAAAAAAAAAAAAAAAf+A////8Af/////wA+AAAAAAAAAAAAAAAD//8B////4A//////gP/4AAAAAAAAAAAAAAH//4D////wB//////Af/wAAAAAAAAAAAAH////wH////gD/////////gAAAAAAAAAAAAP///////////////gP////AAAAAAAAAAAAAf///////////////Af///+AAAAAAAAAAAAA///////////////+A////8AAAAAAAAAAAAB///////////////8B////4AAAAAAAAAAAAD///////////////4D////wAAAAAAAAAAAAH///////////////wH////gAAAAAAAAAAAAP///////////////gP////gAAAAAAAAAAAAf///////////////Af////AAAAAAAAAAAAA/////////////////////+AAAAAAAAAAAAB/////////////////////8AAAAAAAAAAAAD/////////////////////4AAAAAAAAAAAAH/////////////////////wAAAAAAAAAAAAP/////////////////////gAAAAAAAAAAAAf/////////////////////AAAAAAAAAAAAA//////////////////////gAAAAAAAAAAAB//////////4P//////////AAAAAAAAAAAAD/wP///////wf//////////wAAAAAAAAAAAH/Af///////g///////////wAAAAAAAAAAH/+A////////B///////////gAAAAAAAAAAP/8B///////+D///////////AAAAAAAAAAAf/4D///////8H//////////+AAAAAAAAAAA//wH///////4P//////////8AAAAAAAAAAB//gP8B////AAfwB/+Af/+APwAAAAAAAAAAD/4AfwD///+AA/gD/8AAH8AfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    }),
  }),
  chaos: Object.freeze({
    upper: Object.freeze({
      file: 'assets/maps/chaos_mode_map/chaos_mode_map_upper_section.png',
      imgW: 2172, imgH: 622,
      cropTop: 53, cropBottom: 49,
      cell: 8, cols: 271, rows: 77,
      walkableCells: 8353, walkablePct: 40.0,
      componentsFound: 1,
      keptComponentCells: 8353,
      droppedComponentCells: [],
      anchorCell: [116, 72],
      bits:
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAD8AAAAAAAAAAAAAAAAAAAAAAAB/4AAAAAAAAAAD8AAf4AB/AADwAAAAAAAAAAfg4DgADgAB/8AD+AAAAAAAB/wAP8AA/gAD4AAAfAAAAAA//8B8AHwAB/+AB/gAAAAAAA/8B/////8AB8A///gAADgAf/+A+AD/////wD/wAAAAAAAP////////gA8Af//wAP/wAf/+AfAB////////4AAAAAAAH////////wA+AP//8AP/8AP/+AHwB////////8AAAAAAAD////////4B+AH///////////AB+B////////+AAAAAAAB/4H/////8B/AD///////////gA/g/////////gAAAAAAA/wB/////+A/gA/////4P////wAfwf////////8AAAAAAAf4A//gAP/gfwAf////4A////4AP4P/////wB/+AAAAAAAP8Af/gAH///4AP////8Af///8AH///////wA//AAAAAAB/+AP/wAB///8AH////8AH///+AD///////4Af/gAAAAA///AH/4AA///+AD////4AA////AD///////8AP///8AAAf//gD/8AAf///AB////8AAf///wD///////+AH///+AAAP//wB/+AAP///gD////8AAD///4B///+AAf/AD////AAAH/8AA//AAH/////////4AAA/////////AAP/4H////gAAD/+AAf/wAH/////////8AAAf////////gAH///////wAAB//AAP/+AP/////////+AAAP////////wAD///////4AAA//gAH//g/8H////////AAAH//////+D4AB////wAP8AAA//wAD////+D////////gAAD///////B8AA////4AH+AAD//4AB/////A////////wAAB///////g+AAf///4AD/AAH//8AA/////gf///////4AAA///////wfAAP///8AB/gAD//+AAf////wP///////+AAB///////4PwH////+AA/gAB///AAP////wH//////////////////4H///////AAfwAA///gAP////4D//gAAAf///////////8D////8B/gAPwAAf//+Af////8B//wAAAP///////////+B////+AP4Af4AAP///Af////+A//4AAAH///////4AD//A/////AH///8AAH///gP/////Af/8AAAD///////8AB//gf////gD///+AAD///wH////////+AAAB///////+AA////////wB////AAB///4D/////////gAAB////////AAf///////wA////gAA///8B/////////+AAP////////gAP///////4Af///4AAAD/+Af/////////wB/////////wAH///////8AP/AP+AAAB/+AH////////////////////4AD///////+AH/gH/gAAA//AD///////////////////////////////AD/wD/wAAAf/gB///////////////////////////////gB/4B/4AAAP/wA/////wA////////////////////////wA/8A/4AAAH/4Af////wAf///////////////////////4Af+Af8AAAH/8AP////4AP//////////////////8B///8AP///+AAf//+AH////8AAf/////////////////+Af//+AH////AAP///AH////wAAP/////////////////wAP///AH////gAH///gH////wAAD/////////////////4AA///gH////wAD/////////4AAA/////////////8Af/4AAP////////4AB/////////4AAAP////////////+AP/8AAH////////8AA/////////8AAAH////+AAAAB///AH/+AAD////////8AAf////////+AAAD/////AAAAA///gD/+AAA//////wD+AAA/////8A/+AAAB/////AAAAAP//gB//AAAAD////wAHAAAAD///+Af/AAAA/////gAAAAD//wA//gAAAB////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
    }),
    lower: Object.freeze({
      file: 'assets/maps/chaos_mode_map/chaos_mode_map_lower_section.png',
      imgW: 2184, imgH: 848,
      cropTop: 0, cropBottom: 0,
      cell: 8, cols: 273, rows: 106,
      walkableCells: 16389, walkablePct: 56.6,
      componentsFound: 1,
      keptComponentCells: 16389,
      droppedComponentCells: [],
      anchorCell: [153, 8],
      bits:
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8ABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gAfgAAAHgAAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8D/8AAAA/8AH+AAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAB////gAAAH/gA/wAAAAAAAAAAAAAB/8AAAAAAAAAAAAAAAD///8DwB//8AH+AAAAAAAAAAAA////gAAAAAAAAAD8AAAAf////////////4AAeAAAAAAAAH////wAAAAAAAAB/g4AAD////////////////wAAAAAAAA/////AAAAAAAAA/8HgAAf///////////////+AAAAAAB4H////4AAAADgAAf//+AAD////////////////wAAAAAH///////AAAAAfAAH///wAAP////////////////AOAAAA///////4AAAAf4AA///+AAA////////////////4B/+AAH///////AAAAP/gAH///wAAH////////////////AP/wAA///////4AAAB/8AA////AAA////////////////wA//8AH///////gAAAP/gP////4AAH///////////////8AH//gAf//////8AAAB/8B/////gAA///////////////8AAP/8AB////////gAAP/gP////+AAH///////////////gAB//AAH///////8AAB/8B/////wAH///////////////8AAH/wAAP///////gAD/////////8H////////////////gAA/+AAB///////8AAf//////////////////////////8AAH/wAAP///////gAD///////////////////////////gAA/+AAB///////8AAf//////////////////////////8AAH/wAAP///////gAH///////////////4P//////////gAA/+AAB///////8AB/////////////A//B//////////+AAP/4AA////////gAP////////////4H/4P//////////8AH//wAf///////8AB/////////////A//B///////////gB///AD///////wAAAf///////////4AB4P///////////g///4D///////+AAAD////////////AAAB///////////8H///AeD//////wAAAf///////////4AAAP///////////g///8Dwf/////+AAAD////////////AAAB///////////8H///geD//////wAAAf///////////4AAAP///////////g///8Hwf/////+AAAf////////////gAAH///////////8H////+D//////wAAD/////////////+B///////////////////wf//////AAAf/////////////////////////////////////////4AAD//////////////////////////////////////////AAAAA//////////////////////////////////////+A4AAAAH//////////////////////////////////////gAAAAAA//////////////////////////////////////4AAAAAAH//////////////////////////////////////AAAAAAA//////////////////////////////////////4AAAAAAH//////////////////////////////////////AAAAAAA//////////////////////////////////////4AAAAAAP//////////////////////////////////////gAAAAAB//////////////////////////////////////8AAAAAAP//////////////////////////////////////gAAAAAA//////////////////////////////////////4AAAAAAH//////////////////////////////////////AAAAAAA//////////////////////////////////////4AAAAAAH//////////////////////////////////////AAAAAAA//////////////////////////////////////4AAAAAAD/////////////////////////////////////+AAAAAAAP/////////////////////////////////////gAAAAAAA/////////////////////////////////////4AAAAAAAB////////////////////////////////////8AAAAAAAAP////////////////////////////////////gAAAAAAAB////////////////////////////////////8AAAAAAAAP////////////////////////////////////gAAAAAAAB////////////////////////////////////8AAAAAAAAP////////////////////////////////////gAAAAAAAD////////////////////////////////////+AAAAAAAB/////////////////////////////////////8AAAAAAAP/////////////////////////////////////wAAAAAAB/////////////////////////////////////+AAAAAAAf/////////////////////////////////////4AAAAAAH//////////////////////////////////////AAAAAAA//////////////////////////////////////+AAAAAAH//////////////////////////////////////wAAAAAA//////////////////////////////////////+AAAAAAP//////////////////////////////////////wAAAAAB///////////////////////////////////////AAAAAAP//////////////////////////////////////4AAAAAA//////////////////////////////////B////AAAAAAH///////////////gf////////////////4H///4AAAAAA///g///////////4AD////+AP/////////AP//+AAAAAAD//wAH/////////+AAP////gA////////+AA///wAAAAAAH/8AAP/////////gAB////4AB////////wAB//+AAAAAAA//AAB/////////4AAP////AAH///////+AAP//AAAAAAAB/4AAP/////////AAB////4AAP///////wAB//4AAAAAAAP/AAB/////////4AAP////AAB///////+AAB//AAAAAAAAPwAAP/////////AAB////4AAP///////wAAP/wAAAAAAAB+AAB/////////4AAP///4AAB///////+AAB8AAAAAAAAAAAAAP/////////AAA4AfAAAAP///////wAAAAAAAAAAAAAAAAAf////////AAAAAAAAAAAf//////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    }),
  }),});

// Decoded lazily, once per section, and cached. Returns a Uint8Array of cols*rows, 1 = walkable.
const _cache = new Map();
export function deckMaskBits(mode, section) {
  const key = mode + '/' + section;
  const hit = _cache.get(key);
  if (hit) return hit;
  const spec = DECK_MASKS[mode] && DECK_MASKS[mode][section];
  if (!spec) return null;
  const total = spec.cols * spec.rows;
  const out = new Uint8Array(total);
  try {
    const bin = (typeof atob === 'function')
      ? atob(spec.bits)
      : Buffer.from(spec.bits, 'base64').toString('binary');
    for (let i = 0; i < total; i++) {
      const byte = bin.charCodeAt(i >> 3);
      // A truncated or corrupt payload must fail CLOSED (everything blocked), never open:
      // an open failure would drop entities through the floor of a deck that does not exist.
      if (!Number.isFinite(byte)) return _cache.set(key, out), out;
      out[i] = (byte >> (7 - (i & 7))) & 1;
    }
  } catch (_) { out.fill(0); }
  _cache.set(key, out);
  return out;
}

// ══════════════════════════════════════════════════════════════════════════════════════════════
// MAIN-STRIP OBSTACLE MASKS (BATCH 1 follow-up, 2026-07-28)
// ----------------------------------------------------------------------------------------------
// The two MAIN strips keep CITY_WALK_ROWS / CHAOS_WALK_ROWS as the authority for WHERE THE FLOOR
// IS — nothing here changes the band. These masks answer a different question inside that band:
// which cells are a solid prop the player must not walk through. Since the 2026-07-25 P1 audit
// emptied the hand-typed CITY_BLOCK_COLS (their plain-pavement share was 82% / 23% / 0%, i.e.
// close to an inversion of the art) the strips have had NO prop collision at all: kiosks, benches,
// planters, machines and railings were walk-through.
//
// COVERAGE IS PARTIAL AND THAT IS DELIBERATE
//   endless  5.1% of the band, 30 objects
//   chaos    1.6% of the band, 12 objects  (THINNED - see below)
//
// CHAOS IS THINNED TO SOLID CORES (2026-07-28)
// The first Chaos mask blocked 9.0% of the band across 37 objects, and a real browser run proved
// it made the UPPER deck unreachable: the planter garden on the left of that deck walled the whole
// approach off, and the player stopped at the same point every time - 310px of movement in 3000
// frames, 4 of 16 escape directions. An A/B with the mask neutralised reached the deck instantly.
// The fix is geometric, not a special case for the gate: every prop's collider is now its SOLID
// CORE, defined as what survives a one-cell (24 world px) erosion, with cores under 3 cells
// dropped entirely. Big machines, kiosks, pillar bases and the fountain keep a collider; palms,
// small planters, hedges, thin edging and decorative clutter stop blocking - 25 of the 37 objects
// became fully non-blocking and the remaining 12 shrank to their centres. The band is now ONE
// reachable component (7400 cells, 100% of walkable floor) and the authored gate column is
// reachable on all 35 of its walkable rows, 456 world px from spawn with 205px of corridor.
// Five detectors were measured on the shipped art. Every one that covered more also painted
// 57-67% of open plaza solid — the invisible-wall failure again — and was rejected:
//   variance+saturation percentiles   3.7%   missed nearly everything
//   floor-colour model               66.9%   blocked open plaza
//   floor-colour + hysteresis        58.8%   same
//   local contrast (SHIPPED)          5.1%   safe, partial
//   local contrast + region growing  56.9%   growth escaped onto the floor
// The strip is painterly and unevenly lit, so any GLOBAL brightness or saturation rule either
// misses props in the bright half or paints the dim half solid. The shipped detector measures
// structure RELATIVE TO THE LOCAL NEIGHBOURHOOD, which is lighting-invariant, and it is biased to
// under-block on purpose: a missed prop is exactly today's behaviour, while a false wall is a bug
// the player feels on every lap of an infinite map.
//
// Verified visually against both assets before shipping: every blocked cell sits on a real solid
// object, and no blocked cell sits on open pavement.
//
// Same format as DECK_MASKS. Coordinates are SOURCE-IMAGE cells, so the mirror tiling folds into
// them for free — a prop is at the same place in every tile, mirrored where the tile is mirrored.
// ══════════════════════════════════════════════════════════════════════════════════════════════
export const MAIN_OBSTACLES = Object.freeze({
  endless: Object.freeze({
    file: 'assets/maps/new_endless/cyber_megacity.png',
    rows: [210, 415],
    cell: 8, cols: 209, maskRows: 64,
    bandCells: 5434, blockedCells: 275,
    blockedPctOfBand: 5.1,
    bits:
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAwAAwAAAP8AAAAAAAAAcAAAAAAAAAAAAAAABgABgAAAf/AAAAAABgA4PAAAAAAAAAAwAAAAAAYAAAA/+AAAAAADAAAeAAAAAAAAABgAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAMAAAAMAAAAAAAAAAAAAAAAAMAAAAGAAAAAAGAAAAYAAAAAAAAAAAAAAAAAYBgAAMAAAAAAMAAAAwAAAYAAAAAAAAAAAAAwDAAAAAAAAAAAAAABgAAAwAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AADAAAAAAAAAAAAAAAMAAAABgD8AAAAAAA4AAGAAAAAAAAAAAAAAAYAAAAP4H4AAAAAABwAAAAAAAAAAAAAAAAAAAAAAAfwPwAAAAAADgAAAAAAAAAwAAAAcAAAAAAAB4Af4AAAAAADABgDgAAMABgAAAA4AAAAAAADwAP8AAAAAAAADAHAAAYAAAAAAAAAAAAAAAHAAA4AAAAAAAAAAGAAAwAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAMAAB4AAAAAAAAAAAAAwAYAAAAAAAGAAAAAAAAAAwAAAAAAAAAAAABgAAAAAAAAAMAAAAAAAAABgAAAAAAAAAAYADAAAwAAAAAAAAAMAAAAAAAAAAAAAAAAAAwAGAABgAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
  }),
  chaos: Object.freeze({
    file: 'assets/maps/chaos_mode_map/chaos_map.png',
    rows: [135, 410],
    cell: 8, cols: 209, maskRows: 55,
    // THINNED to solid cores 2026-07-28 - see the header note.
    bandCells: 7524, blockedCells: 124,
    blockedPctOfBand: 1.6,
    bits:
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIABgAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAQADAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAgAGAAAAAAAAAAAAAAAABwAAAAAAAAABAAABAAMAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAeAAAAAAAAAAAAYAAAGAAAAAAAAAAAAAAAAAwAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAwAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAgAAAAAAACAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  }),});

const _obstCache = new Map();
export function mainObstacleBits(mode) {
  const hit = _obstCache.get(mode);
  if (hit) return hit;
  const spec = MAIN_OBSTACLES[mode];
  if (!spec) return null;
  const total = spec.cols * spec.maskRows;
  const out = new Uint8Array(total);
  try {
    const bin = (typeof atob === 'function')
      ? atob(spec.bits)
      : Buffer.from(spec.bits, 'base64').toString('binary');
    for (let i = 0; i < total; i++) {
      const byte = bin.charCodeAt(i >> 3);
      // A truncated payload fails OPEN here, the opposite of the deck masks: this file only ever
      // ADDS obstacles to a strip that already has a valid floor band, so the safe degradation is
      // today's behaviour (no prop collision), never a strip the player cannot walk on at all.
      if (!Number.isFinite(byte)) return _obstCache.set(mode, out), out;
      out[i] = (byte >> (7 - (i & 7))) & 1;
    }
  } catch (_) { out.fill(0); }
  _obstCache.set(mode, out);
  return out;
}
