/**
 * EnemyWeaponCatalog.js — PHENIX: NULL EDEN
 * ──────────────────────────────────────────
 * Stage 1: Data-only weapon catalog.
 * No gameplay behavior — just definitions for future integration.
 * Each entry maps a weapon sprite to its intended owners, behavior type,
 * and stat baseline.
 */

// ── Weapon behavior types ────────────────────────────────────────────
export const WEAPON_BEHAVIOR = Object.freeze({
  PROJECTILE:           'projectile',
  FAST_PROJECTILE:      'fast_projectile',
  HEAVY_PROJECTILE:     'heavy_projectile',
  PIERCING_PROJECTILE:  'piercing_projectile',
  ARC_PROJECTILE:       'arc_projectile',
  BEAM:                 'beam',
  SHORT_PULSE:          'short_pulse',
  SLASH_WAVE:           'slash_wave',
  SLASH_ARC:            'slash_arc',
  ORB_EXPLOSION:        'orb_explosion',
  BOOMERANG:            'boomerang',
});

// ── Weapon definitions ───────────────────────────────────────────────
export const ENEMY_WEAPONS = Object.freeze([
  {
    id: 'void_ember_comet',
    displayName: 'Void Ember Comet',
    spritePath: 'assets/enemies/weapons/sprites/void_ember_comet.png',
    ownerEnemyTypes: ['forge-mauler', 'ember-scarab'],
    behavior: WEAPON_BEHAVIOR.ARC_PROJECTILE,
    damage: 10,
    speed: 380,
    cooldown: 2.8,
    telegraphTime: 0,
    hitShape: 'circle_aoe',
    impactEffect: 'ember_burst',
    notes: 'Medium AoE impact, ember burst. Screen shake boss version only.',
  },
  {
    id: 'null_sigil_beam',
    displayName: 'Null Sigil Beam',
    spritePath: 'assets/enemies/weapons/sprites/null_sigil_beam.png',
    ownerEnemyTypes: ['null-hierophant', 'rift-eye'],
    behavior: WEAPON_BEHAVIOR.BEAM,
    damage: 6,
    speed: 0,
    cooldown: 4.0,
    telegraphTime: 0.8,
    hitShape: 'line_beam',
    impactEffect: 'null_sigil_flash',
    notes: 'Telegraph line first, then continuous tick damage.',
  },
  {
    id: 'violet_spectral_needle',
    displayName: 'Violet Spectral Needle',
    spritePath: 'assets/enemies/weapons/sprites/violet_spectral_needle.png',
    ownerEnemyTypes: ['rail-reaper', 'amethyst-fang', 'void-widow'],
    behavior: WEAPON_BEHAVIOR.FAST_PROJECTILE,
    damage: 14,
    speed: 720,
    cooldown: 2.2,
    telegraphTime: 0,
    hitShape: 'line_projectile',
    impactEffect: 'violet_trail_flash',
    notes: 'Fast thin shot, high damage, small hitbox. Warning line for boss version.',
  },
  {
    id: 'eden_star_lance',
    displayName: 'Eden Star Lance',
    spritePath: 'assets/enemies/weapons/sprites/eden_star_lance.png',
    ownerEnemyTypes: ['solar-tyrant'],
    behavior: WEAPON_BEHAVIOR.PIERCING_PROJECTILE,
    damage: 22,
    speed: 500,
    cooldown: 5.0,
    telegraphTime: 1.0,
    hitShape: 'line_projectile',
    impactEffect: 'golden_star_burst',
    notes: 'Rare heavy star-lance, piercing, bright impact. Boss elite phase only.',
  },
  {
    id: 'abyss_rift_blade',
    displayName: 'Abyss Rift Blade',
    spritePath: 'assets/enemies/weapons/sprites/abyss_rift_blade.png',
    ownerEnemyTypes: ['pale-bloodknight', 'abyss-maw'],
    behavior: WEAPON_BEHAVIOR.SLASH_WAVE,
    damage: 16,
    speed: 450,
    cooldown: 2.6,
    telegraphTime: 0.5,
    hitShape: 'cone_slash',
    impactEffect: 'dark_blade_wave',
    notes: 'Blade wave / cone slash. Telegraph before swing.',
  },
  {
    id: 'cryo_shard_lance',
    displayName: 'Cryo Shard Lance',
    spritePath: 'assets/enemies/weapons/sprites/cryo_shard_lance.png',
    ownerEnemyTypes: ['cryo-warden', 'cryo-claw'],
    behavior: WEAPON_BEHAVIOR.PROJECTILE,
    damage: 10,
    speed: 480,
    cooldown: 2.0,
    telegraphTime: 0,
    hitShape: 'line_projectile',
    impactEffect: 'frost_burst',
    notes: 'Frost damage, icy burst. Slow only if existing slow system supports it.',
  },
  {
    id: 'solar_halo_bolt',
    displayName: 'Solar Halo Bolt',
    spritePath: 'assets/enemies/weapons/sprites/solar_halo_bolt.png',
    ownerEnemyTypes: ['solar-tyrant', 'solar-stinger', 'forge-mauler'],
    behavior: WEAPON_BEHAVIOR.PROJECTILE,
    damage: 8,
    speed: 520,
    cooldown: 1.6,
    telegraphTime: 0,
    hitShape: 'circle_projectile',
    impactEffect: 'golden_flash',
    notes: 'Readable golden shot, medium/light damage.',
  },
  {
    id: 'toxic_data_spear',
    displayName: 'Toxic Data Spear',
    spritePath: 'assets/enemies/weapons/sprites/toxic_data_spear.png',
    ownerEnemyTypes: ['rail-reaper', 'toxin-leech', 'volt-rat'],
    behavior: WEAPON_BEHAVIOR.PROJECTILE,
    damage: 12,
    speed: 520,
    cooldown: 2.4,
    telegraphTime: 0,
    hitShape: 'line_projectile',
    impactEffect: 'green_glitch_burst',
    notes: 'Green glitch burst. No poison/drain unless existing system.',
  },
  {
    id: 'magma_reaver_lance',
    displayName: 'Magma Reaver Lance',
    spritePath: 'assets/enemies/weapons/sprites/magma_reaver_lance.png',
    ownerEnemyTypes: ['forge-mauler', 'reactor-colossus', 'ember-scarab'],
    behavior: WEAPON_BEHAVIOR.HEAVY_PROJECTILE,
    damage: 18,
    speed: 350,
    cooldown: 3.2,
    telegraphTime: 0.6,
    hitShape: 'circle_aoe',
    impactEffect: 'magma_explosion',
    notes: 'Heavy fire hit, ember burst, small screen shake for boss version.',
  },
  {
    id: 'arc_circuit_beam',
    displayName: 'Arc Circuit Beam',
    spritePath: 'assets/enemies/weapons/sprites/arc_circuit_beam.png',
    ownerEnemyTypes: ['null-hierophant', 'reactor-colossus', 'cryo-warden', 'pulse-burrower', 'volt-rat'],
    behavior: WEAPON_BEHAVIOR.BEAM,
    damage: 5,
    speed: 0,
    cooldown: 3.5,
    telegraphTime: 0.6,
    hitShape: 'line_beam',
    impactEffect: 'electric_arc_flash',
    notes: 'Telegraphed beam/pulse, continuous or short tick damage.',
  },
  {
    id: 'aether_crescent_chakram',
    displayName: 'Aether Crescent Chakram',
    spritePath: 'assets/enemies/weapons/sprites/aether_crescent_chakram.png',
    ownerEnemyTypes: ['cryo-warden', 'pulse-burrower'],
    behavior: WEAPON_BEHAVIOR.BOOMERANG,
    damage: 8,
    speed: 400,
    cooldown: 3.0,
    telegraphTime: 0,
    hitShape: 'circle_projectile',
    impactEffect: 'aether_shimmer',
    notes: 'Curving/returning projectile, light-medium damage.',
  },
  {
    id: 'prism_wing_bolt',
    displayName: 'Prism Wing Bolt',
    spritePath: 'assets/enemies/weapons/sprites/prism_wing_bolt.png',
    ownerEnemyTypes: ['amethyst-fang'],
    behavior: WEAPON_BEHAVIOR.PROJECTILE,
    damage: 7,
    speed: 560,
    cooldown: 1.8,
    telegraphTime: 0,
    hitShape: 'circle_projectile',
    impactEffect: 'prism_sparkle',
    notes: 'Fast elegant bolt, light-medium damage.',
  },
  {
    id: 'blacknet_scythe_arc',
    displayName: 'Blacknet Scythe Arc',
    spritePath: 'assets/enemies/weapons/sprites/blacknet_scythe_arc.png',
    ownerEnemyTypes: ['pale-bloodknight', 'void-widow'],
    behavior: WEAPON_BEHAVIOR.SLASH_ARC,
    damage: 15,
    speed: 0,
    cooldown: 2.8,
    telegraphTime: 0.5,
    hitShape: 'arc_slash',
    impactEffect: 'dark_scythe_trail',
    notes: 'Telegraphed arc slash, medium/heavy damage.',
  },
  {
    id: 'seraph_vector_javelin',
    displayName: 'Seraph Vector Javelin',
    spritePath: 'assets/enemies/weapons/sprites/seraph_vector_javelin.png',
    ownerEnemyTypes: ['rail-reaper', 'solar-tyrant', 'solar-stinger'],
    behavior: WEAPON_BEHAVIOR.PIERCING_PROJECTILE,
    damage: 16,
    speed: 600,
    cooldown: 3.0,
    telegraphTime: 0.4,
    hitShape: 'line_projectile',
    impactEffect: 'golden_pierce_flash',
    notes: 'Piercing line attack, warning line for boss version.',
  },
  {
    id: 'null_rupture_orb',
    displayName: 'Null Rupture Orb',
    spritePath: 'assets/enemies/weapons/sprites/null_rupture_orb.png',
    ownerEnemyTypes: ['null-hierophant', 'pale-bloodknight', 'abyss-maw', 'rift-eye'],
    behavior: WEAPON_BEHAVIOR.ORB_EXPLOSION,
    damage: 20,
    speed: 200,
    cooldown: 4.5,
    telegraphTime: 0.8,
    hitShape: 'circle_aoe',
    impactEffect: 'null_rupture_explosion',
    notes: 'Slow orb, warning ring, circular AoE explosion. No invisible radius.',
  },
]);

// ── Boss weapon assignments ──────────────────────────────────────────
export const BOSS_WEAPON_MAP = Object.freeze({
  'cryo-warden':     ['cryo_shard_lance', 'arc_circuit_beam', 'aether_crescent_chakram'],
  'forge-mauler':    ['magma_reaver_lance', 'void_ember_comet', 'solar_halo_bolt'],
  'null-hierophant': ['null_sigil_beam', 'arc_circuit_beam', 'null_rupture_orb'],
  'pale-bloodknight':['abyss_rift_blade', 'blacknet_scythe_arc', 'null_rupture_orb'],
  'rail-reaper':     ['violet_spectral_needle', 'toxic_data_spear', 'seraph_vector_javelin'],
  'reactor-colossus':['arc_circuit_beam', 'magma_reaver_lance', 'solar_halo_bolt'],
  'solar-tyrant':    ['solar_halo_bolt', 'seraph_vector_javelin', 'eden_star_lance'],
});

// ── Mini enemy weapon assignments ────────────────────────────────────
export const MINI_WEAPON_MAP = Object.freeze({
  'abyss-maw':       ['null_rupture_orb', 'abyss_rift_blade'],
  'amethyst-fang':   ['violet_spectral_needle', 'prism_wing_bolt'],
  'cryo-claw':       ['cryo_shard_lance'],
  'ember-scarab':    ['void_ember_comet', 'magma_reaver_lance'],
  'pulse-burrower':  ['arc_circuit_beam', 'aether_crescent_chakram'],
  'rift-eye':        ['null_sigil_beam', 'null_rupture_orb'],
  'solar-stinger':   ['solar_halo_bolt', 'seraph_vector_javelin'],
  'toxin-leech':     ['toxic_data_spear'],
  'void-widow':      ['blacknet_scythe_arc', 'violet_spectral_needle'],
  'volt-rat':        ['arc_circuit_beam', 'toxic_data_spear'],
});

// ── Helper: lookup weapon by id ──────────────────────────────────────
const _weaponIndex = new Map(ENEMY_WEAPONS.map(w => [w.id, w]));
export function getWeaponById(id) { return _weaponIndex.get(id) || null; }

// ── Helper: get all weapons for an enemy type ────────────────────────
export function getWeaponsForEnemy(enemyId) {
  const ids = BOSS_WEAPON_MAP[enemyId] || MINI_WEAPON_MAP[enemyId] || [];
  return ids.map(id => _weaponIndex.get(id)).filter(Boolean);
}
